### ISSUE TITLE
Simppeli → Micro.blog compatibility

### ISSUE THREAD

**Issue by amongthestones** [samikeijonen/simppeli#3]
Simppeli is one of the cleanest and best-looking themes I've found for a personal blog, with great typography and formatting options. Have you thought about adding support for more post formats for easier use for [Micro.blog](http://micro.blog) users? Basically just allowing titleless posts that can display something in the archives list view.

**Comment by samikeijonen** [comment]
Thanks!

I'm 99% I won't be adding support for post formats. That could done via child theme though.
